# Generated by Django 2.2.3 on 2019-10-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
