# Generated by Django 2.2.3 on 2019-10-19 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directmessages', '0002_auto_20191012_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmessage',
            options={'ordering': ['-sent_at']},
        ),
    ]
