# Generated by Django 2.2.3 on 2019-08-13 06:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage('/media/images'), upload_to='')),
                ('caption', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
