# Generated by Django 2.2.3 on 2019-08-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('caption', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='thumbnailimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
