# Generated by Django 2.2.3 on 2019-09-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190822_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='teammates',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
